import { expect, test } from './fixtures'

test('compact cards show only text; Enter saves, a separate Enter creates a sibling', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
  await page.locator('[data-cell-id="root"]').click()
  const count = await page.locator('[data-cell-id]').count()
  await page.keyboard.press('Tab')
  await page.getByRole('textbox').fill('Компактная мысль')
  const id = await page.locator('[data-active="true"]').getAttribute('data-cell-id')
  const card = page.locator(`[data-cell-id="${id}"]`)
  await page.keyboard.press('Enter')
  await expect(page.getByRole('textbox')).toHaveCount(0)
  await expect(page.locator('main')).toBeFocused()
  await expect(page.getByRole('status')).toContainText('Enter — соседняя клеточка')
  await expect(page.locator('[data-cell-id]')).toHaveCount(count + 1)
  await expect(card).toHaveAttribute('data-active', 'true')
  await expect(card).toHaveText('Компактная мысль')
  await expect(card).toHaveCSS('padding-left', '10px')
  await expect(card).toHaveCSS('padding-top', '8px')
  await expect.poll(() => card.evaluate(element => element.clientHeight)).toBeLessThan(46)
  await expect(card).toHaveCSS('background-color', 'rgb(255, 227, 161)')
  await expect(card).toHaveCSS('box-shadow', 'rgba(237, 172, 39, 0.2) 0px 0px 0px 3px, rgba(65, 71, 46, 0.04) 0px 5px 15px 0px')
  // Удержание клавиши после commit не должно создавать случайный sibling.
  await page.locator('main').dispatchEvent('keydown', { key: 'Enter', repeat: true })
  await expect(page.locator('[data-cell-id]')).toHaveCount(count + 1)
  await page.keyboard.press('Space')
  await expect(card).toHaveAttribute('data-status', 'done')
  await expect(card).toHaveText('Компактная мысль')
  await expect(card.locator('.cell-text')).toHaveCSS('text-decoration-line', 'none')
  await expect(card).toHaveCSS('background-color', 'rgb(199, 232, 167)')
  await expect(card).toHaveCSS('box-shadow', 'rgba(98, 140, 57, 0.2) 0px 0px 0px 3px, rgba(65, 71, 46, 0.04) 0px 5px 15px 0px')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('textbox')).toBeFocused()
  await expect(page.locator('[data-cell-id]')).toHaveCount(count + 2)
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-cell-id]')).toHaveCount(count + 1)

  await card.dblclick()
  await expect(page.getByRole('textbox')).toBeFocused()
  await expect(card).not.toHaveClass(/cell-draggable/)
  const editor = page.getByRole('textbox')
  await expect(editor).toHaveCSS('cursor', 'text')
  await expect(card).toHaveCSS('border-color', 'rgb(98, 140, 57)')
  await expect(card).toHaveCSS('box-shadow', 'rgba(98, 140, 57, 0.267) 0px 0px 0px 3px')
  const bounds = (await editor.boundingBox())!
  await page.mouse.move(bounds.x + 4, bounds.y + bounds.height / 2)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width - 4, bounds.y + bounds.height / 2, { steps: 8 })
  await page.mouse.up()
  await expect(editor).toBeFocused()
  expect(await editor.evaluate(element => (element as HTMLTextAreaElement).selectionEnd - (element as HTMLTextAreaElement).selectionStart)).toBeGreaterThan(0)
  await expect(page.getByTestId('drop-indicator')).toHaveCount(0)
  await editor.fill('Компактная мысль после правки')
  await page.keyboard.press('Enter')
  await expect(card).toHaveText('Компактная мысль после правки')
  await expect(page.locator('[data-cell-id]')).toHaveCount(count + 1)
  await page.screenshot({ path: 'test-results/compact-cells.png' })
})
