import { expect, test } from './fixtures'

test('compact cards show only text; Enter saves, a separate Enter creates a sibling', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
  await page.locator('[data-cell-id="root"]').click()
  const count = await page.locator('[data-cell-id]').count()
  await page.keyboard.press('Tab')
  await page.getByRole('textbox').fill('Компактная мысль')
  const id = await page.locator('[data-active="true"]').getAttribute('data-cell-id')
  const card = page.locator(`[data-cell-id="${id}"]`)
  await page.keyboard.press('Enter')
  await expect(page.getByRole('textbox')).toHaveCount(0)
  await expect(page.locator('main')).toBeFocused()
  await expect(page.getByRole('status')).toContainText('Enter — соседняя клеточка')
  await expect(page.locator('[data-cell-id]')).toHaveCount(count + 1)
  await expect(card).toHaveAttribute('data-active', 'true')
  await expect(card).toHaveText('Компактная мысль')
  expect(await card.getAttribute('title')).toBeNull()
  expect(await card.evaluate(element => element.closest('[title]') !== null)).toBe(false)
  await expect(card.locator('[title]')).toHaveCount(0)
  await expect(card).toHaveAttribute('aria-label', 'Компактная мысль. Открыто')
  await expect(card).toHaveCSS('padding-left', '10px')
  await expect(card).toHaveCSS('padding-top', '8px')
  await expect.poll(() => card.evaluate(element => element.clientHeight)).toBeLessThan(46)
  await expect(card).toHaveCSS('background-color', 'rgb(255, 227, 161)')
  await expect(card.locator('.cell-text')).toHaveCSS('color', 'rgb(32, 37, 28)')
  await expect(card).toHaveCSS('border-color', 'rgb(168, 107, 8)')
  await expect(card).toHaveCSS('box-shadow', 'rgb(168, 107, 8) 0px 0px 0px 2px, rgba(237, 172, 39, 0.2) 0px 0px 0px 5px, rgba(65, 71, 46, 0.14) 0px 6px 16px 0px')
  // Удержание клавиши после commit не должно создавать случайный sibling.
  await page.locator('main').dispatchEvent('keydown', { key: 'Enter', repeat: true })
  await expect(page.locator('[data-cell-id]')).toHaveCount(count + 1)
  await page.keyboard.press('Space')
  await expect(card).toHaveAttribute('data-status', 'done')
  expect(await card.getAttribute('title')).toBeNull()
  await expect(card).toHaveAttribute('aria-label', 'Компактная мысль. Готово')
  await expect(card).toHaveText('Компактная мысль')
  await expect(card.locator('.cell-text')).toHaveCSS('text-decoration-line', 'none')
  await expect(card).toHaveCSS('background-color', 'rgb(199, 232, 167)')
  await expect(card.locator('.cell-text')).toHaveCSS('color', 'rgb(32, 37, 28)')
  await expect(card).toHaveCSS('box-shadow', 'rgb(72, 120, 44) 0px 0px 0px 2px, rgba(98, 140, 57, 0.2) 0px 0px 0px 5px, rgba(65, 71, 46, 0.14) 0px 6px 16px 0px')
  const measure = () => card.evaluate(element => {
    const text = element.querySelector('.cell-text') as HTMLElement
    return { width: element.clientWidth, height: element.clientHeight, textWidth: text.offsetWidth, textHeight: text.offsetHeight }
  })
  const selectedSize = await measure()
  await page.keyboard.press('ArrowLeft')
  await expect(card).toHaveAttribute('data-active', 'false')
  await expect(card).toHaveCSS('box-shadow', 'rgba(65, 71, 46, 0.03) 0px 4px 12px 0px')
  expect(await measure()).toEqual(selectedSize)
  await card.click()
  await expect(card).toHaveAttribute('data-active', 'true')
  expect(await measure()).toEqual(selectedSize)
  await page.keyboard.press('Enter')
  await expect(page.getByRole('textbox')).toBeFocused()
  await expect(page.locator('[data-cell-id]')).toHaveCount(count + 2)
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-cell-id]')).toHaveCount(count + 1)

  await card.dblclick()
  await expect(page.getByRole('textbox')).toBeFocused()
  await expect(card).not.toHaveClass(/cell-draggable/)
  const editor = page.getByRole('textbox')
  await expect(editor).toHaveCSS('cursor', 'text')
  await expect(editor).toHaveCSS('color', 'rgb(32, 37, 28)')
  await expect(card).toHaveCSS('border-color', 'rgb(72, 120, 44)')
  await expect(card).toHaveCSS('box-shadow', 'rgb(72, 120, 44) 0px 0px 0px 2px, rgba(98, 140, 57, 0.2) 0px 0px 0px 5px, rgba(65, 71, 46, 0.14) 0px 6px 16px 0px')
  const bounds = (await editor.boundingBox())!
  await page.mouse.move(bounds.x + 4, bounds.y + bounds.height / 2)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width - 4, bounds.y + bounds.height / 2, { steps: 8 })
  await page.mouse.up()
  await expect(editor).toBeFocused()
  expect(await editor.evaluate(element => (element as HTMLTextAreaElement).selectionEnd - (element as HTMLTextAreaElement).selectionStart)).toBeGreaterThan(0)
  await expect(page.getByTestId('drop-indicator')).toHaveCount(0)
  await editor.fill('Компактная мысль после правки')
  await page.keyboard.press('Enter')
  await expect(card).toHaveText('Компактная мысль после правки')
  await expect(page.locator('[data-cell-id]')).toHaveCount(count + 1)
  await page.screenshot({ path: 'test-results/compact-cells.png' })
})
