import { expect, test, namedContext, type Page } from './fixtures'

const root = (page: Page) => page.locator('[data-cell-id="root"]')
async function ready(page: Page) {
  await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
}
async function newDiagram(page: Page, title: string) {
  await page.getByRole('button', { name: 'Схемы', exact: true }).click()
  await page.getByLabel('Поиск или название новой схемы', { exact: true }).fill(title)
  await page.getByRole('button', { name: 'Создать', exact: true }).click()
  await expect(page).toHaveURL(/\/diagram\/[0-9a-f-]{36}$/)
  await ready(page)
  await expect(root(page)).toHaveAttribute('data-text', title)
  return page.url()
}

test('create, switch, share and rename diagrams without mixing data, presence or undo', async ({ page, browser }) => {
  await page.goto('/')
  await ready(page)
  const legacyTitle = await root(page).getAttribute('data-text')
  const legacyCount = await page.locator('[data-cell-id]').count()
  const firstUrl = await newDiagram(page, 'Первая отдельная схема')
  await expect(page.locator('[data-cell-id]')).toHaveCount(1)
  await root(page).click()
  await page.keyboard.press('Tab')
  await page.getByRole('textbox').fill('Только в первой')
  await page.keyboard.press('Enter')
  const secondUrl = await newDiagram(page, 'Вторая отдельная схема')
  expect(secondUrl).not.toBe(firstUrl)
  await expect(page.locator('[data-cell-id]')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Отменить действие', exact: true })).toBeDisabled()

  const context = await namedContext(browser)
  const peer = await context.newPage()
  try {
    await peer.goto(firstUrl)
    await ready(peer)
    await expect(peer.locator('[data-text="Только в первой"]')).toHaveCount(1)
    await expect(page.locator('.avatars span')).toHaveCount(1)
    await expect(peer.locator('.avatars span')).toHaveCount(1)
    await page.getByRole('button', { name: 'Схемы', exact: true }).click()
    await page.getByRole('link', { name: 'Первая отдельная схема', exact: true }).click()
    await ready(page)
    await expect(page.locator('.avatars span')).toHaveCount(2)
    await root(page).dblclick()
    await page.getByRole('textbox').fill('Название из корня')
    // Уход в переключатель сохраняет draft до перехода.
    await page.getByRole('button', { name: 'Схемы', exact: true }).click()
    await expect(peer.locator('[data-cell-id="root"]')).toHaveAttribute('data-text', 'Название из корня')
    await page.getByRole('link', { name: 'Вторая отдельная схема', exact: true }).click()
    await ready(page)
    await expect(root(page)).toHaveAttribute('data-text', 'Вторая отдельная схема')
    await page.getByRole('button', { name: 'Схемы', exact: true }).click()
    await expect(page.getByRole('link', { name: 'Название из корня', exact: true })).toBeVisible()
    await page.screenshot({ path: 'test-results/diagrams.png' })
    await page.keyboard.press('Escape')
    await expect(page.locator('main')).toBeFocused()
    await page.goBack()
    await ready(page)
    await expect(root(page)).toHaveAttribute('data-text', 'Название из корня')
    await page.goto('/')
    await ready(page)
    await expect(root(page)).toHaveAttribute('data-text', legacyTitle!)
    await expect(page.locator('[data-cell-id]')).toHaveCount(legacyCount)
  } finally { await context.close() }
})

test('closing the picker and file dialogs returns keyboard commands to the active cell', async ({ page }) => {
  await page.goto('/')
  await ready(page)
  await newDiagram(page, 'Проверка фокуса')
  await page.keyboard.press('Tab')
  await page.getByRole('textbox').fill('Текущая клеточка')
  await page.keyboard.press('Enter')
  const cell = page.locator('[data-text="Текущая клеточка"]')
  const trigger = page.getByRole('button', { name: 'Схемы', exact: true })
  for (const action of ['escape', 'close', 'open', 'delete', 'download']) {
    await trigger.focus()
    await page.keyboard.press('Enter')
    const catalog = page.getByRole('dialog', { name: 'Выбор схемы для редактирования', exact: true })
    await expect(catalog).toBeVisible()
    if (action === 'escape') await page.keyboard.press('Escape')
    else if (action === 'close') await page.getByRole('button', { name: 'Закрыть список схем' }).click()
    else if (action === 'download') {
      const download = page.waitForEvent('download')
      await catalog.getByRole('button', { name: 'Сохранить в файл', exact: true }).click()
      await download
    } else if (action === 'open') {
      const chooser = page.waitForEvent('filechooser')
      await catalog.getByRole('button', { name: 'Заменить из файла', exact: true }).click()
      await chooser
      await expect(page.locator('dialog[open]')).toHaveCount(0)
      await page.getByLabel('Файл схемы', { exact: true }).dispatchEvent('cancel')
    } else {
      await catalog.getByRole('button', { name: 'Удалить схему', exact: true }).click()
      await expect(page.locator('dialog[open]')).toHaveCount(1)
      await expect(page.locator('dialog[open]')).toHaveJSProperty('open', true)
      await expect.poll(() => page.evaluate(() => !!document.activeElement?.closest('dialog[open]'))).toBe(true)
      await page.getByRole('button', { name: 'Отмена', exact: true }).click()
    }
    await expect(page.locator('dialog[open]')).toHaveCount(0)
    await expect(page.locator('main')).toBeFocused()
    await expect(cell).toHaveAttribute('data-active', 'true')
    await page.keyboard.press('F2')
    await expect(page.getByRole('textbox', { name: 'Текст клеточки' })).toHaveValue('Текущая клеточка')
    await page.keyboard.press('Escape')
  }
})

test('offline diagram links and cached list stay isolated; branding and invalid links work', async ({ page, context }) => {
  await page.goto('/')
  await ready(page)
  const a = await newDiagram(page, 'Offline A')
  const b = await newDiagram(page, 'Offline B')
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  await expect(page.locator('.brand img')).toBeVisible()
  expect(await page.locator('.brand img').evaluate((element: HTMLImageElement) => element.naturalWidth)).toBe(256)
  expect((await page.request.get('/favicon.ico')).status()).toBe(200)
  expect((await page.request.get('/favicon-32.png')).headers()['content-type']).toContain('image/png')
  await page.setViewportSize({ width: 375, height: 667 })
  await page.getByRole('button', { name: 'Схемы', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeInViewport()
  await expect(page.getByRole('button', { name: 'Создать', exact: true })).toBeInViewport()
  await page.screenshot({ path: 'test-results/diagrams-mobile.png' })
  await page.keyboard.press('Escape')
  await context.setOffline(true)
  await page.reload()
  await ready(page)
  await expect(root(page)).toHaveAttribute('data-text', 'Offline B')
  await expect(page.locator('.brand img')).toBeVisible()
  await page.getByRole('button', { name: 'Схемы', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Создать', exact: true })).toBeDisabled()
  await expect(page.getByRole('alert')).toContainText('сохранённый список')
  await page.getByRole('link', { name: 'Offline A', exact: true }).click()
  await ready(page)
  await expect(page).toHaveURL(a)
  await root(page).dblclick()
  await page.getByRole('textbox').fill('Offline A изменена')
  // Удерживаем предыдущую транзакцию: следующая запись точно останется
  // незавершённой до reload, независимо от скорости диска в тестовой среде.
  await page.evaluate(async id => {
    await new Promise<void>((resolve, reject) => {
      const request = indexedDB.open(`decompose:${id}:v1`)
      request.onerror = () => reject(request.error)
      request.onsuccess = () => {
        const transaction = request.result.transaction('updates', 'readwrite')
        const store = transaction.objectStore('updates')
        const keepAlive = () => { store.get(0).onsuccess = keepAlive }
        keepAlive()
        resolve()
      }
    })
  }, new URL(a).pathname.split('/').at(-1))
  await page.keyboard.press('Enter')
  // Немедленный reload может прервать последнюю IndexedDB-транзакцию.
  await page.reload()
  await ready(page)
  await expect(root(page)).toHaveAttribute('data-text', 'Offline A изменена')
  expect(await page.evaluate(id => sessionStorage.getItem(`decompose:pending:${id}`), new URL(a).pathname.split('/').at(-1))).toBeNull()
  // Переход через UI дожидается IndexedDB перед уходом со страницы.
  await page.getByRole('button', { name: 'Схемы', exact: true }).click()
  await page.getByRole('link', { name: 'Offline B', exact: true }).click()
  await ready(page)
  await expect(root(page)).toHaveAttribute('data-text', 'Offline B')
  await page.getByRole('button', { name: 'Схемы', exact: true }).click()
  await page.getByRole('link', { name: 'Offline A изменена', exact: true }).click()
  await ready(page)
  await expect(root(page)).toHaveAttribute('data-text', 'Offline A изменена')
  await page.reload()
  await ready(page)
  await expect(root(page)).toHaveAttribute('data-text', 'Offline A изменена')
  await page.goto(b)
  await ready(page)
  await expect(root(page)).toHaveAttribute('data-text', 'Offline B')
  await context.setOffline(false)
  await page.goto(a)
  await ready(page)
  await expect(page.getByTestId('connection')).toHaveAttribute('data-connected', 'true')
  await expect.poll(async () => (await (await page.request.get(`/api/diagrams/${new URL(a).pathname.split('/').at(-1)}`)).json()).title).toBe('Offline A изменена')
  await page.goto('/?diagram=00000000-0000-4000-8000-000000000000')
  await expect(page.getByRole('alert')).toContainText('Схема не найдена')
  await expect(page.locator('[data-cell-id]')).toHaveCount(0)
  await page.goto('/?diagram=invalid')
  await expect(page.getByRole('alert')).toContainText('Некорректная ссылка')
})
