import { expect, test, type Page } from '@playwright/test'

async function open(page: Page) {
  await page.goto('/')
  await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
  await expect(page.getByTestId('connection')).toHaveAttribute('data-connected', 'true')
}

async function create(page: Page, text: string, key = 'Tab') {
  await page.keyboard.press(key)
  await page.getByRole('textbox').fill(text)
  const id = (await page.locator('[data-active="true"]').getAttribute('data-cell-id'))!
  await page.keyboard.press('Enter')
  const cell = page.locator(`[data-cell-id="${id}"]`)
  await expect(cell).toHaveAttribute('data-text', text)
  return cell
}

test('keyboard and toolbar history, native draft undo, cancellation and reload', async ({ page }) => {
  await open(page)
  const undo = page.getByRole('button', { name: 'Отменить действие', exact: true })
  const redo = page.getByRole('button', { name: 'Повторить действие', exact: true })
  await expect(undo).toBeDisabled()
  await expect(redo).toBeDisabled()
  await page.locator('[data-cell-id="root"]').click()
  const cell = await create(page, 'История текста')
  await expect(undo).toBeEnabled()
  await page.keyboard.press('F2')
  await expect(undo).toBeDisabled()
  // Одна вставка: браузер сам выбирает группировку посимвольного ввода.
  await page.keyboard.insertText(' draft')
  await expect(page.getByRole('textbox')).toHaveValue('История текста draft')
  await page.keyboard.press('Control+z')
  await expect(page.getByRole('textbox')).toHaveValue('История текста')
  await expect(cell).toHaveAttribute('data-text', 'История текста')
  await page.keyboard.press('Control+Shift+z')
  await expect(page.getByRole('textbox')).toHaveValue('История текста draft')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Control+z')
  await expect(cell).toHaveAttribute('data-text', 'История текста')
  await page.keyboard.press('Control+y')
  await expect(cell).toHaveAttribute('data-text', 'История текста draft')
  await page.keyboard.press('Space')
  await expect(cell).toHaveAttribute('data-status', 'done')
  await undo.click()
  await expect(cell).toHaveAttribute('data-status', 'open')
  await expect(page.locator('main')).toBeFocused()
  await redo.click()
  await expect(cell).toHaveAttribute('data-status', 'done')
  await expect(cell.locator('.cell-text')).toHaveCSS('text-decoration-line', 'none')

  // Escape не должен оставлять отменённое создание в undo/redo.
  await page.keyboard.press('Tab')
  await page.keyboard.press('Escape')
  await page.keyboard.press('Control+z')
  await expect(cell).toHaveAttribute('data-status', 'open')
  await page.keyboard.press('F2')
  await page.getByRole('textbox').fill('Новое действие вместо redo')
  await page.keyboard.press('Enter')
  await expect(redo).toBeDisabled()
  await page.reload()
  await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
  await expect(cell).toHaveAttribute('data-text', 'Новое действие вместо redo')
  await expect(undo).toBeDisabled()
  await expect(redo).toBeDisabled()
})

test('undo and redo reorder, reparent, subtree deletion and creation synchronize without remote history', async ({ browser }) => {
  const lc = await browser.newContext()
  const rc = await browser.newContext()
  const left = await lc.newPage()
  const right = await rc.newPage()
  const dialogs: string[] = []
  left.on('dialog', async dialog => {
    dialogs.push(dialog.message())
    await dialog.dismiss()
  })
  try {
    await open(left)
    await open(right)
    await left.locator('[data-cell-id="root"]').click()
    const parent = await create(left, 'Родитель с историей')
    const parentId = (await parent.getAttribute('data-cell-id'))!
    const first = await create(left, 'Первый с историей')
    const firstId = (await first.getAttribute('data-cell-id'))!
    const second = await create(left, 'Второй с историей', 'Enter')
    const secondId = (await second.getAttribute('data-cell-id'))!
    const remoteSecond = right.locator(`[data-cell-id="${secondId}"]`)
    await expect(remoteSecond).toHaveAttribute('data-text', 'Второй с историей')
    await expect(right.getByRole('button', { name: 'Отменить действие', exact: true })).toBeDisabled()
    await left.keyboard.press('Control+ArrowUp')
    await expect(remoteSecond).toHaveAttribute('data-order', '0')
    await left.keyboard.press('Control+z')
    await expect(remoteSecond).toHaveAttribute('data-order', '1')
    await left.keyboard.press('Control+ArrowRight')
    await expect(remoteSecond).toHaveAttribute('data-parent-id', firstId)
    await left.keyboard.press('Control+z')
    await expect(remoteSecond).toHaveAttribute('data-parent-id', parentId)
    await left.keyboard.press('Control+Shift+z')
    await expect(remoteSecond).toHaveAttribute('data-parent-id', firstId)
    await parent.click()
    await left.keyboard.press('Delete')
    await expect(parent).toHaveCount(0)
    await expect(remoteSecond).toHaveCount(0)
    await left.keyboard.press('Control+z')
    await expect(parent).toHaveAttribute('data-active', 'true')
    await expect(remoteSecond).toHaveAttribute('data-parent-id', firstId)
    await left.keyboard.press('Control+y')
    await expect(parent).toHaveCount(0)
    await expect(remoteSecond).toHaveCount(0)
    await expect(left.locator('[data-active="true"]')).toHaveCount(1)
    await left.keyboard.press('Control+z')
    await expect(parent).toHaveAttribute('data-active', 'true')
    await left.getByRole('button', { name: 'Действия с клеточкой', exact: true }).click()
    await left.getByRole('button', { name: 'Удалить', exact: true }).click()
    await expect(parent).toHaveCount(0)
    await expect(remoteSecond).toHaveCount(0)
    await left.keyboard.press('Control+z')
    await expect(parent).toHaveAttribute('data-active', 'true')
    await expect(remoteSecond).toHaveAttribute('data-parent-id', firstId)
    expect(dialogs).toEqual([])
    const newCell = await create(left, 'Создать и отменить')
    const newId = (await newCell.getAttribute('data-cell-id'))!
    await left.keyboard.press('Control+z')
    await expect(newCell).toHaveAttribute('data-text', '')
    await left.keyboard.press('Control+z')
    await expect(newCell).toHaveCount(0)
    await left.keyboard.press('Control+Shift+z')
    await expect(newCell).toHaveAttribute('data-cell-id', newId)
    await left.keyboard.press('Control+Shift+z')
    await expect(newCell).toHaveAttribute('data-text', 'Создать и отменить')
    await expect(right.locator(`[data-cell-id="${newId}"]`)).toHaveAttribute('data-text', 'Создать и отменить')
    await expect(right.getByRole('button', { name: 'Отменить действие', exact: true })).toBeDisabled()
  } finally {
    await lc.close()
    await rc.close()
  }
})
