import { test, expect } from './fixtures'

for (const shortcut of ['Control+o', 'Meta+o']) {
  test(`${shortcut} opens the picker, commits the draft and returns focus to the canvas`, async ({ page }) => {
    const response = await page.request.post('/api/diagrams', { data: { title: 'До редактирования' } })
    await page.goto(`/diagram/${(await response.json()).id}`)
    const canvas = page.locator('main')
    await expect(canvas).toHaveAttribute('data-ready', 'true')
    await page.locator('[data-cell-id="root"]').click()
    await page.keyboard.press('F2')
    await page.getByRole('textbox', { name: 'Текст клеточки' }).fill('Сохранено перед выбором')
    await page.keyboard.press(shortcut)
    const picker = page.getByRole('dialog', { name: 'Выбор схемы для редактирования' })
    await expect(picker).toBeVisible()
    await expect(picker.locator('.current-scheme-name')).toHaveText('Сохранено перед выбором')
    await expect(page.getByRole('tab', { name: 'Схемы', exact: true })).toBeFocused()
    const search = page.getByRole('searchbox', { name: 'Поиск или название новой схемы' })
    await search.fill('Не сбрасывать поиск')
    await page.keyboard.press(shortcut)
    await expect(search).toHaveValue('Не сбрасывать поиск')
    await expect(search).toBeFocused()
    await expect(page.locator('dialog[open]')).toHaveCount(1)
    // В поле search первый Escape очищает ввод штатным поведением браузера.
    await page.getByRole('tab', { name: 'Схемы', exact: true }).focus()
    await page.keyboard.press('Escape')
    await expect(canvas).toBeFocused()
    await expect(page.locator('[data-cell-id="root"]')).toContainText('Сохранено перед выбором')
    await expect(page.locator('[data-cell-id]')).toHaveCount(1)
    await page.keyboard.press(shortcut)
    await expect(picker).toBeVisible()
    await expect(search).toHaveValue('')
  })
}

test('open shortcut uses the physical key and ignores extra modifiers, composition and repeats', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
  const dispatch = (extra: Pick<KeyboardEventInit, 'shiftKey' | 'altKey' | 'isComposing' | 'repeat'>) => page.evaluate(extra => {
    const event = new KeyboardEvent('keydown', { code: 'KeyO', key: 'щ', ctrlKey: true, bubbles: true, cancelable: true, ...extra })
    document.activeElement!.dispatchEvent(event)
    return event.defaultPrevented
  }, extra)
  for (const extra of [{ shiftKey: true }, { altKey: true }, { isComposing: true }]) {
    expect(await dispatch(extra)).toBe(false)
    await expect(page.locator('dialog[open]')).toHaveCount(0)
  }
  expect(await dispatch({ repeat: true })).toBe(true)
  await expect(page.locator('dialog[open]')).toHaveCount(0)
  expect(await dispatch({})).toBe(true)
  await expect(page.getByRole('dialog', { name: 'Выбор схемы для редактирования' })).toBeVisible()
})

test('open shortcut does not stack the picker over another modal', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
  await page.getByRole('button', { name: 'Изменить имя', exact: true }).click()
  const identity = page.getByRole('dialog', { name: 'Твоё имя', exact: true })
  const name = identity.getByRole('textbox', { name: 'Имя', exact: true })
  await name.fill('Несохранённое имя')
  await page.keyboard.press('Control+o')
  await expect(page.locator('dialog[open]')).toHaveCount(1)
  await expect(identity).toBeVisible()
  await expect(name).toHaveValue('Несохранённое имя')
  await expect(name).toBeFocused()
})

for (const mode of [
  { path: '/', tab: 'Схемы' },
  { path: '/tracker/TABS-301', tab: 'Задачи' },
]) {
  test(`picker selects the document mode on every opening, including choose=1: ${mode.tab}`, async ({ page }) => {
    await page.goto(`${mode.path}?choose=1`)
    await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
    const selected = page.getByRole('tab', { name: mode.tab, exact: true })
    await expect(selected).toHaveAttribute('aria-selected', 'true')
    await expect(selected).toBeFocused()
    expect(new URL(page.url()).searchParams.has('choose')).toBe(false)
    const url = page.url()
    await page.getByRole('tab', { name: 'Файлы', exact: true }).click()
    await expect(page.getByRole('tabpanel', { name: 'Файлы', exact: true })).toBeVisible()
    expect(page.url()).toBe(url)
    await page.keyboard.press('Escape')
    await expect(page.locator('main')).toBeFocused()
    await page.getByRole('button', { name: 'Схемы', exact: true }).click()
    await expect(selected).toHaveAttribute('aria-selected', 'true')
    await expect(selected).toBeFocused()
    await expect(page.getByRole('tabpanel')).toHaveCount(1)
  })
}

test('tabs support manual keyboard activation without search stealing focus', async ({ page }) => {
  await page.goto('/?choose=1')
  const tabs = page.getByRole('tablist', { name: 'Раздел каталога' })
  const diagrams = tabs.getByRole('tab', { name: 'Схемы', exact: true })
  const tracker = tabs.getByRole('tab', { name: 'Задачи', exact: true })
  const files = tabs.getByRole('tab', { name: 'Файлы', exact: true })
  await expect(diagrams).toBeFocused()
  await page.keyboard.press('ArrowLeft')
  await expect(files).toBeFocused()
  await expect(diagrams).toHaveAttribute('aria-selected', 'true')
  await page.keyboard.press('ArrowRight')
  await expect(diagrams).toBeFocused()
  await page.keyboard.press('End')
  await expect(files).toBeFocused()
  await page.keyboard.press('Space')
  await expect(files).toHaveAttribute('aria-selected', 'true')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Открыть файл на диске', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(files).toBeFocused()
  await page.keyboard.press('Home')
  await expect(diagrams).toBeFocused()
  await page.keyboard.press('ArrowRight')
  await expect(tracker).toBeFocused()
  const loaded = page.waitForResponse(response => response.url().includes('/api/tracker?'))
  await page.keyboard.press('Enter')
  await loaded
  await expect(tracker).toHaveAttribute('aria-selected', 'true')
  await expect(tracker).toBeFocused()
  await expect(tabs.locator('[tabindex="0"]')).toHaveCount(1)
  await expect(page.getByRole('tabpanel')).toHaveAttribute('aria-labelledby', (await tracker.getAttribute('id'))!)
  await page.keyboard.press('Tab')
  await expect(page.getByRole('searchbox', { name: 'Поиск задач' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.locator('main')).toBeFocused()
})

test('compact management header wraps long names and actions without overflow', async ({ page }) => {
  const title = 'ОченьДлинноеНазваниеБезПробелов'.repeat(10)
  const response = await page.request.post('/api/diagrams', { data: { title } })
  expect(response.ok()).toBe(true)
  const { id } = await response.json()
  await page.goto(`/diagram/${id}?choose=1`)
  const dialog = page.getByRole('dialog', { name: 'Выбор схемы для редактирования', exact: true })
  const current = dialog.getByRole('region', { name: 'Текущая схема', exact: true })
  await expect(current.locator('.current-scheme-name')).toHaveText(title)
  await expect(current.getByRole('heading')).toHaveCount(0)
  await expect(current.getByText('Текущая схема', { exact: true })).toHaveCount(0)
  await expect(current).toHaveCSS('border-top-width', '0px')
  await expect(current).toHaveCSS('background-color', 'rgb(255, 245, 214)')
  await expect(dialog.getByRole('heading', { name: 'Выбор схемы для редактирования' })).toBeVisible()
  await expect(dialog.getByText('Открыть другую', { exact: true })).toHaveCount(0)
  const badge = await current.locator('.storage-kind').boundingBox()
  const name = await current.locator('.current-scheme-name').boundingBox()
  expect(badge!.y + badge!.height).toBeLessThan(name!.y)
  const actionRows = () => current.getByRole('button').evaluateAll(buttons => buttons.map(button => button.getBoundingClientRect().top))
  const desktopRows = await actionRows()
  expect(new Set(desktopRows).size).toBe(1)
  await page.screenshot({ path: 'test-results/management-long-name-desktop.png' })
  await page.setViewportSize({ width: 375, height: 667 })
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  expect(new Set(await actionRows()).size).toBeGreaterThan(1)
  await expect(dialog).toBeInViewport()
  await page.screenshot({ path: 'test-results/management-long-name-mobile.png' })
})

test('catalog search fields and action buttons use consistent sizing without redundant tracker labels', async ({ page }) => {
  await page.goto('/?choose=1')
  const picker = page.getByRole('dialog', { name: 'Выбор схемы для редактирования' })
  const search = picker.getByRole('searchbox')
  const metrics = (element: Element) => {
    const style = getComputedStyle(element)
    return { height: element.getBoundingClientRect().height, fontSize: style.fontSize,
      lineHeight: style.lineHeight, padding: style.padding, fontFamily: style.fontFamily }
  }
  const diagramSearch = await search.evaluate(metrics)
  const create = picker.getByRole('button', { name: 'Создать', exact: true })
  expect(await create.evaluate(metrics)).toEqual(await picker.locator('.scheme-actions button').first().evaluate(metrics))
  expect((await create.boundingBox())!.height).toBe(diagramSearch.height)
  await page.screenshot({ path: 'test-results/management-diagrams-controls.png' })
  await picker.getByRole('tab', { name: 'Задачи', exact: true }).click()
  await expect(search).toHaveAccessibleName('Поиск задач')
  expect(await search.evaluate(metrics)).toEqual(diagramSearch)
  await expect(picker.getByText('Поиск задач', { exact: true })).toHaveCount(0)
  await expect(picker.getByText('Последние изменённые деревья задач', { exact: true })).toHaveCount(0)
  await expect(search).toHaveAttribute('autocomplete', 'off')
  await expect(picker.getByText('Ищем задачи…', { exact: true })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/management-tracker-controls.png' })
})

test('one field filters diagram names and creates only on an explicit action', async ({ page }) => {
  const ids: string[] = []
  for (const title of ['Поиск ёж Север', 'Поиск ЁЖ Юг', 'Поиск заяц']) {
    const response = await page.request.post('/api/diagrams', { data: { title } })
    expect(response.ok()).toBe(true)
    ids.push((await response.json()).id)
  }
  await page.goto('/?choose=1')
  const search = page.getByRole('searchbox', { name: 'Поиск или название новой схемы', exact: true })
  const list = page.getByRole('navigation', { name: 'Список схем', exact: true })
  await expect(page.getByText('Поиск или название новой схемы', { exact: true })).toHaveCount(0)
  await expect(search).toHaveAttribute('autocomplete', 'off')
  await expect(search).toHaveAttribute('autocorrect', 'off')
  await expect(search).toHaveAttribute('spellcheck', 'false')
  await expect(page.locator('.diagram-create')).toHaveJSProperty('noValidate', true)
  await expect(page.locator('.open-scheme')).toHaveCSS('border-top-width', '0px')
  await expect(list.getByRole('link', { name: 'Поиск заяц', exact: true })).toBeVisible()
  const searchBounds = await search.boundingBox(), listBounds = await list.boundingBox()
  expect(searchBounds!.y + searchBounds!.height).toBeLessThan(listBounds!.y)
  let creations = 0
  page.on('request', request => { if (request.method() === 'POST' && new URL(request.url()).pathname === '/api/diagrams') creations++ })
  await search.fill('  пОиСК ёЖ  ')
  await expect(list.getByRole('link')).toHaveText(['Поиск ёж Север', 'Поиск ЁЖ Юг'])
  await search.fill('Нет такой схемы')
  await expect(list.getByRole('link')).toHaveCount(0)
  await expect(page.getByText('Схемы не найдены.', { exact: true })).toBeVisible()
  await search.press('Enter')
  await expect(page.getByRole('button', { name: 'Создать', exact: true })).toBeFocused()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(creations).toBe(0)
  await search.fill('Поиск ёж Север')
  await page.getByRole('tab', { name: 'Файлы', exact: true }).click()
  await page.getByRole('tab', { name: 'Схемы', exact: true }).click()
  await expect(search).toHaveValue('Поиск ёж Север')
  await expect(list.getByRole('link')).toHaveText(['Поиск ёж Север'])
  await search.focus()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Создать', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/\/diagram\/[\da-f-]{36}$/)
  await expect(page.locator('[data-cell-id="root"]')).toHaveAttribute('data-text', 'Поиск ёж Север')
  expect(ids).not.toContain(new URL(page.url()).pathname.split('/').at(-1))
  expect(creations).toBe(1)
  await page.getByRole('button', { name: 'Схемы', exact: true }).click()
  await expect(search).toHaveValue('')
})

test('diagram search works in the cached offline catalog while creation stays disabled', async ({ page, context }) => {
  await page.request.post('/api/diagrams', { data: { title: 'Offline поиск ёж' } })
  await page.goto('/?choose=1')
  const list = page.getByRole('navigation', { name: 'Список схем', exact: true })
  await expect(list.getByRole('link', { name: 'Offline поиск ёж', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await context.setOffline(true)
  await page.getByRole('button', { name: 'Схемы', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('сохранённый список')
  const search = page.getByRole('searchbox', { name: 'Поиск или название новой схемы', exact: true })
  await expect(search).toBeEnabled()
  await search.fill('offline ПОИСК')
  await expect(list.getByRole('link')).toHaveText(['Offline поиск ёж'])
  await expect(page.getByRole('button', { name: 'Создать', exact: true })).toBeDisabled()
  await search.fill('Offline отсутствующая схема')
  await expect(list.getByRole('link')).toHaveCount(0)
  await search.press('Enter')
  await expect(search).toBeFocused()
  await search.press('ArrowDown')
  await expect(search).toBeFocused()
  await search.fill('')
  await expect.poll(() => list.getByRole('link').count()).toBeGreaterThan(1)
})

test('search arrows enter the results and Enter opens by name without creating', async ({ page }) => {
  const ids: string[] = []
  for (let index = 1; index <= 3; index++) {
    const response = await page.request.post('/api/diagrams', { data: { title: `Клавиатурный поиск ${index}` } })
    ids.push((await response.json()).id)
  }
  await page.goto('/?choose=1')
  let creations = 0
  page.on('request', request => { if (request.method() === 'POST' && new URL(request.url()).pathname === '/api/diagrams') creations++ })
  const search = page.getByRole('searchbox', { name: 'Поиск или название новой схемы', exact: true })
  const list = page.getByRole('navigation', { name: 'Список схем' })
  const links = list.getByRole('link')
  await search.fill('Клавиатурный поиск')
  await expect(links).toHaveCount(3)
  await search.press('ArrowUp')
  await expect(links.last()).toBeFocused()
  await expect(search).toHaveValue('Клавиатурный поиск')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(new RegExp(`/diagram/${ids[2]}$`))
  await page.getByRole('button', { name: 'Схемы', exact: true }).click()
  await search.fill('Клавиатурный поиск')
  await search.press('ArrowDown')
  await expect(links.first()).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(links.nth(1)).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(new RegExp(`/diagram/${ids[1]}$`))
  await page.getByRole('button', { name: 'Схемы', exact: true }).click()
  await search.fill('Клавиатурный поиск 1')
  await expect(links).toHaveCount(1)
  await search.dispatchEvent('keydown', { key: 'Enter', isComposing: true })
  await expect(search).toBeFocused()
  await expect(page.getByRole('dialog')).toBeVisible()
  await search.press('Enter')
  await expect(page).toHaveURL(new RegExp(`/diagram/${ids[0]}$`))
  expect(creations).toBe(0)
})

test('Enter waits for results, then only focuses Create; a separate press creates once', async ({ page }) => {
  let release!: () => void
  const loading = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/diagrams', async route => {
    if (route.request().method() !== 'GET') { await route.continue(); return }
    await loading
    await route.fulfill({ json: [] })
  })
  await page.goto('/?choose=1')
  let creations = 0
  page.on('request', request => { if (request.method() === 'POST' && new URL(request.url()).pathname === '/api/diagrams') creations++ })
  const search = page.getByRole('searchbox', { name: 'Поиск или название новой схемы', exact: true })
  const create = page.getByRole('button', { name: 'Создать', exact: true })
  await search.fill('Создать после выбора кнопки')
  await expect(page.getByText('Загружаем список…', { exact: true })).toBeVisible()
  await search.press('Enter')
  await expect(search).toBeFocused()
  release()
  await expect(page.getByText('Схемы не найдены.', { exact: true })).toBeVisible()
  await search.fill('')
  await search.press('Enter')
  await expect(search).toBeFocused()
  await expect(create).toBeDisabled()
  await search.fill('Создать после выбора кнопки')
  await page.keyboard.down('Enter')
  await expect(create).toBeFocused()
  await page.keyboard.down('Enter')
  await page.keyboard.up('Enter')
  // Даже неявный submit формы не создаёт документ: действие принадлежит кнопке.
  await page.locator('.diagram-create').dispatchEvent('submit')
  expect(creations).toBe(0)
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/\/diagram\/[\da-f-]{36}$/)
  await expect(page.locator('[data-cell-id="root"]')).toHaveAttribute('data-text', 'Создать после выбора кнопки')
  expect(creations).toBe(1)
})

for (const mode of ['diagrams', 'tracker'] as const) {
  test(`catalog uses arrows within the list and Tab between controls: ${mode}`, async ({ page }) => {
    const ids: string[] = []
    for (let index = 1; index <= 3; index++) {
      const response = mode === 'diagrams'
        ? await page.request.post('/api/diagrams', { data: { title: `Стрелки схемы ${index}` } })
        : await page.request.post(`/api/tracker/ARROWS-${index}`)
      expect(response.ok()).toBe(true)
      ids.push((await response.json()).id)
    }
    await page.goto(`${mode === 'diagrams' ? `/diagram/${ids[1]}` : '/tracker/ARROWS-2'}?choose=1`)
    const search = page.getByRole('searchbox', { name: mode === 'diagrams' ? 'Поиск или название новой схемы' : 'Поиск задач', exact: true })
    const list = page.getByRole('navigation', { name: mode === 'diagrams' ? 'Список схем' : 'Список задач', exact: true })
    const links = list.getByRole('link')
    await search.fill(mode === 'diagrams' ? 'Стрелки схемы' : 'ARROWS-')
    await expect(links).toHaveCount(3)
    await expect(search).toBeFocused()
    await page.keyboard.press('Tab')
    if (mode === 'diagrams') {
      await expect(page.getByRole('button', { name: 'Создать', exact: true })).toBeFocused()
      await page.keyboard.press('Tab')
    }
    await expect(list.locator('[aria-current="page"]')).toBeFocused()
    await expect(list.locator('a[tabindex="0"]')).toHaveCount(1)
    const url = page.url()
    await page.keyboard.press('Home')
    await expect(links.first()).toBeFocused()
    await page.keyboard.press('ArrowUp')
    await expect(links.first()).toBeFocused()
    await page.keyboard.press('ArrowDown')
    await expect(links.nth(1)).toBeFocused()
    await page.keyboard.press('End')
    await expect(links.last()).toBeFocused()
    await page.keyboard.press('ArrowDown')
    await expect(links.last()).toBeFocused()
    expect(page.url()).toBe(url)
    await page.keyboard.press('Tab')
    await expect.poll(() => list.evaluate(element => element.contains(document.activeElement))).toBe(false)
    await page.keyboard.press('Shift+Tab')
    await expect(links.last()).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    if (mode === 'diagrams') await expect(page.getByRole('button', { name: 'Создать', exact: true })).toBeFocused()
    else await expect(search).toBeFocused()
    // Фильтрация не переводит фокус в список; пустая выдача не создаёт остановку по Tab.
    await search.fill('Ничего не найдено')
    await expect(links).toHaveCount(0)
    await expect(search).toBeFocused()
    await page.keyboard.press('Tab')
    if (mode === 'diagrams') await page.keyboard.press('Tab')
    await expect.poll(() => list.evaluate(element => element.contains(document.activeElement))).toBe(false)
    await search.fill(mode === 'diagrams' ? 'Стрелки схемы 1' : 'ARROWS-1')
    await expect(links).toHaveCount(1)
    await page.keyboard.press('Tab')
    if (mode === 'diagrams') await page.keyboard.press('Tab')
    await expect(links.first()).toBeFocused()
    await expect(links.first()).toHaveAttribute('tabindex', '0')
    const href = await links.first().getAttribute('href')
    const target = await page.evaluate(href => new URL(href!, document.baseURI).href, href)
    await page.keyboard.press('Enter')
    await expect(page).toHaveURL(target)
    await expect(page.locator('main')).toBeFocused()
  })
}

test('switching tabs animates only the bottom edge and respects reduced motion', async ({ page }) => {
  await page.route('**/api/diagrams', route => route.fulfill({ json: Array.from({ length: 20 }, (_, index) => ({
    id: `00000000-0000-4000-8000-${String(index).padStart(12, '0')}`, title: `Схема ${index}`,
  })) }))
  await page.goto('/?choose=1')
  const dialog = page.getByRole('dialog', { name: 'Выбор схемы для редактирования', exact: true })
  await expect(page.getByRole('navigation', { name: 'Список схем' }).getByRole('link')).toHaveCount(20)
  const list = page.getByRole('navigation', { name: 'Список схем' })
  await list.getByRole('link').first().focus()
  await page.keyboard.press('End')
  await expect(list.getByRole('link').last()).toBeFocused()
  expect(await list.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
  await expect.poll(() => dialog.evaluate(element => element.getAnimations().length)).toBe(0)
  const frames = await dialog.evaluate(async element => {
    const read = () => ({ top: element.getBoundingClientRect().top, height: element.getBoundingClientRect().height,
      tabs: element.querySelector('[role="tablist"]')!.getBoundingClientRect().top })
    const frames = [read()]
    element.querySelector<HTMLButtonElement>('#catalog-tab-files')!.click()
    const start = performance.now()
    while (performance.now() - start < 400) {
      await new Promise(requestAnimationFrame)
      frames.push(read())
    }
    return frames
  })
  const first = frames[0], last = frames.at(-1)!
  expect(first.height - last.height).toBeGreaterThan(30)
  expect(frames.some(frame => frame.height < first.height - 2 && frame.height > last.height + 2)).toBe(true)
  for (const frame of frames) {
    expect(Math.abs(frame.top - first.top)).toBeLessThan(1)
    expect(Math.abs(frame.tabs - first.tabs)).toBeLessThan(1)
  }
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(dialog).toHaveCSS('transition-duration', '0s')
  await page.getByRole('tab', { name: 'Схемы', exact: true }).click()
  await expect.poll(() => dialog.evaluate(element => element.getBoundingClientRect().top)).toBe(first.top)
  await page.setViewportSize({ width: 375, height: 480 })
  await expect(dialog).toBeInViewport()
  expect(await dialog.evaluate(element => element.getBoundingClientRect().bottom)).toBeLessThanOrEqual(480)
  expect(await dialog.locator('.management-content').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
})

test('dialog focus has no browser outline and keyboard controls have an inset indicator', async ({ page }) => {
  await page.goto('/?choose=1')
  const dialog = page.getByRole('dialog', { name: 'Выбор схемы для редактирования', exact: true })
  const tab = page.getByRole('tab', { name: 'Файлы', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.evaluate((element: HTMLDialogElement) => element.focus())
  await expect(dialog).toBeFocused()
  await expect(dialog).toHaveCSS('outline-style', 'none')
  await tab.focus()
  await page.keyboard.press('Space')
  await expect(tab).toHaveCSS('outline-style', 'none')
  await expect(tab).toHaveCSS('box-shadow', 'rgb(88, 115, 72) 0px 0px 0px 2px inset')
  await page.emulateMedia({ forcedColors: 'active' })
  await expect(tab).toHaveCSS('outline-style', 'solid')
  await expect(tab).toHaveCSS('outline-offset', '-3px')
  await expect(dialog).toHaveCSS('outline-style', 'none')
})
