import { expect, test, namedContext, type Page } from './fixtures'

const root = (page: Page) => page.locator('[data-cell-id="root"]')
const editor = (page: Page) => page.getByRole('textbox', { name: 'Текст клеточки' })
async function ready(page: Page) {
  await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
  await expect(page.getByTestId('connection')).toHaveAttribute('data-connected', 'true')
}
async function newDiagram(page: Page, title: string) {
  const response = await page.request.post('/api/diagrams', { data: { title } })
  expect(response.ok()).toBe(true)
  return `/?diagram=${(await response.json()).id}`
}
async function toggleAlignment(page: Page) {
  await page.getByRole('button', { name: 'Действия с клеточкой', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Текст карточек по центру' }).click()
}
async function aligned(page: Page, value: string) {
  await expect.poll(() => page.locator('.cell-text').evaluateAll(cells => [...new Set(cells.map(cell => getComputedStyle(cell).textAlign))])).toEqual([value])
}

test('alignment toggles by its label and by keyboard, not only by the checkbox', async ({ page }) => {
  await page.goto(await newDiagram(page, 'Клик по подписи'))
  await ready(page)
  const menu = page.getByRole('button', { name: 'Действия с клеточкой', exact: true })
  for (const expected of ['left', 'center']) {
    await menu.click()
    const label = page.locator('.diagram-settings label')
    const bounds = (await label.boundingBox())!
    // Правая часть подписи, заведомо за пределами самого checkbox.
    await label.click({ position: { x: bounds.width - 12, y: bounds.height / 2 } })
    await aligned(page, expected)
    await expect(menu).toHaveAttribute('aria-expanded', 'false')
  }
  await menu.click()
  const checkbox = page.getByRole('checkbox', { name: 'Текст карточек по центру' })
  await checkbox.focus()
  await page.keyboard.press('Space')
  await aligned(page, 'left')
  await menu.click()
  await checkbox.click()
  await aligned(page, 'center')
})

test('Shift+Enter inserts native soft breaks; commit, cancel, history, paste and collaboration preserve them', async ({ page, context, browser }) => {
  const url = await newDiagram(page, 'ПерваяВторая')
  await page.goto(url)
  await ready(page)
  const peerContext = await namedContext(browser)
  try {
    const peer = await peerContext.newPage()
    await peer.goto(url)
    await ready(peer)
    const initialHeight = await root(page).evaluate(cell => cell.getBoundingClientRect().height)
    await root(page).dblclick()
    await editor(page).evaluate((input: HTMLTextAreaElement) => input.setSelectionRange(6, 6))
    await page.keyboard.press('Shift+Enter')
    await expect(editor(page)).toHaveValue('Первая\nВторая')
    await expect(editor(page)).toBeFocused()
    await expect(page.locator('[data-cell-id]')).toHaveCount(1)
    await expect(root(peer)).toHaveAttribute('data-text', 'ПерваяВторая')
    await page.keyboard.press('Control+z')
    await expect(editor(page)).toHaveValue('ПерваяВторая')
    await page.keyboard.press('Control+Shift+z')
    await expect(editor(page)).toHaveValue('Первая\nВторая')
    await page.keyboard.press('Enter')
    await expect(editor(page)).toHaveCount(0)
    await expect(root(peer)).toHaveAttribute('data-text', 'Первая\nВторая')
    await expect.poll(() => root(page).evaluate(cell => cell.getBoundingClientRect().height)).toBeGreaterThan(initialHeight)
    await expect(root(page).locator('.cell-text')).toHaveCSS('white-space', 'pre-wrap')
    await expect(page.getByRole('button', { name: 'Схемы', exact: true })).toContainText('Первая Вторая')
    const id = new URL(page.url()).pathname.split('/').at(-1)
    expect((await (await page.request.get(`/api/diagrams/${id}`)).json()).title).toBe('Первая Вторая')
    await page.getByRole('button', { name: 'Отменить действие', exact: true }).click()
    await expect(root(peer)).toHaveAttribute('data-text', 'ПерваяВторая')
    await page.getByRole('button', { name: 'Повторить действие', exact: true }).click()
    await expect(root(peer)).toHaveAttribute('data-text', 'Первая\nВторая')
    await root(page).dblclick()
    await page.keyboard.press('Shift+Enter')
    await page.keyboard.press('Escape')
    await expect(root(page)).toHaveAttribute('data-text', 'Первая\nВторая')
    await root(page).dblclick()
    await context.grantPermissions(['clipboard-read', 'clipboard-write'])
    await page.evaluate(() => navigator.clipboard.writeText('Из буфера\r\n\r\nТретья строка'))
    await editor(page).selectText()
    await page.keyboard.press('Control+v')
    await expect(editor(page)).toHaveValue('Из буфера\n\nТретья строка')
    await page.keyboard.press('Control+Enter')
    await expect(root(peer)).toHaveAttribute('data-text', 'Из буфера\n\nТретья строка')
    await page.reload()
    await ready(page)
    await expect(root(page)).toHaveAttribute('data-text', 'Из буфера\n\nТретья строка')
    await expect(page.locator('[data-cell-id]')).toHaveCount(1)
  } finally { await peerContext.close() }
})

test('alignment is shared per diagram, undoable without changing selection, durable and editable offline', async ({ page, context, browser }) => {
  const a = await newDiagram(page, 'Выравнивание A')
  const b = await newDiagram(page, 'Выравнивание B')
  await page.goto(a)
  await ready(page)
  await root(page).click()
  await page.keyboard.press('Tab')
  await editor(page).fill('Первая\nВторая')
  await page.keyboard.press('Enter')
  const child = page.locator('[data-active="true"]')
  const childId = await child.getAttribute('data-cell-id')
  await aligned(page, 'center')
  const peerContext = await namedContext(browser)
  try {
    const peer = await peerContext.newPage()
    await peer.goto(a)
    await ready(peer)
    await toggleAlignment(page)
    await aligned(page, 'left')
    await aligned(peer, 'left')
    await expect(peer.getByRole('button', { name: 'Отменить действие', exact: true })).toBeDisabled()
    await page.getByRole('button', { name: 'Отменить действие', exact: true }).click()
    await aligned(peer, 'center')
    await expect(child).toHaveAttribute('data-cell-id', childId!)
    await page.getByRole('button', { name: 'Повторить действие', exact: true }).click()
    await aligned(peer, 'left')
    await expect(child).toHaveAttribute('data-cell-id', childId!)
    await page.keyboard.press('F2')
    await expect(editor(page)).toHaveCSS('text-align', 'left')
    await page.keyboard.press('Escape')
    await page.reload()
    await ready(page)
    await aligned(page, 'left')
    await page.goto(b)
    await ready(page)
    await aligned(page, 'center')
    await page.getByRole('button', { name: 'Схемы', exact: true }).click()
    await page.getByRole('link', { name: 'Выравнивание A', exact: true }).click()
    await ready(page)
    await aligned(page, 'left')
    await page.evaluate(async () => { await navigator.serviceWorker.ready })
    await context.setOffline(true)
    await expect(page.getByTestId('connection')).toHaveAttribute('data-connected', 'false')
    await toggleAlignment(page)
    await aligned(page, 'center')
    await page.reload()
    await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
    await aligned(page, 'center')
    await expect(page.locator(`[data-cell-id="${childId}"]`)).toHaveAttribute('data-text', 'Первая\nВторая')
    await context.setOffline(false)
    await aligned(peer, 'center')
    await toggleAlignment(peer)
    await aligned(page, 'left')
  } finally { await peerContext.close() }
})

test('a guest must introduce themselves to change diagram alignment, with cancellation leaving it unchanged', async ({ page, browser }) => {
  const url = await newDiagram(page, 'Гостевое выравнивание')
  const context = await browser.newContext()
  try {
    const guest = await context.newPage()
    await guest.goto(url)
    await ready(guest)
    await guest.setViewportSize({ width: 375, height: 667 })
    await toggleAlignment(guest)
    await expect(guest.getByRole('dialog', { name: 'Представься' })).toBeVisible()
    await guest.keyboard.press('Escape')
    await aligned(guest, 'center')
    await toggleAlignment(guest)
    await guest.getByRole('textbox', { name: 'Имя', exact: true }).fill('Автор настройки')
    await guest.keyboard.press('Enter')
    await aligned(guest, 'left')
    await guest.reload()
    await ready(guest)
    await aligned(guest, 'left')
    await guest.getByRole('button', { name: 'Действия с клеточкой', exact: true }).click()
    await expect(guest.getByRole('checkbox', { name: 'Текст карточек по центру' })).not.toBeChecked()
  } finally { await context.close() }
})
