import { test, expect, type Page } from '@playwright/test'

const root = (page: Page) => page.locator('[data-cell-id="root"]')
const ready = async (page: Page) => {
  await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
}
async function rename(page: Page, text: string) {
  await root(page).dblclick()
  await page.getByRole('textbox', { name: 'Текст клеточки' }).fill(text)
  await page.keyboard.press('Enter')
  await expect(root(page)).toHaveAttribute('data-text', text)
}
async function picker(page: Page, section: 'Схемы' | 'Задачи') {
  await page.getByRole('button', { name: 'Схемы', exact: true }).click()
  await page.getByRole('group', { name: 'Раздел каталога' }).getByRole('button', { name: section, exact: true }).click()
}
async function navigate(page: Page, path: string) {
  await page.evaluate(path => {
    history.pushState(null, '', path)
    dispatchEvent(new PopStateEvent('popstate'))
  }, path)
}

test('first tracker visit asks for a name, cancel creates nothing, retry initializes the key once', async ({ page }) => {
  await page.goto('/tracker/ui-100')
  const prompt = page.getByRole('dialog', { name: 'Представься', exact: true })
  await expect(prompt).toBeVisible()
  expect((await page.request.get('/api/tracker/UI-100')).status()).toBe(404)
  await prompt.getByRole('button', { name: 'Отмена' }).click()
  await expect(page.getByText('Дерево задачи ещё не создано.')).toBeVisible()
  expect((await page.request.get('/api/tracker/UI-100')).status()).toBe(404)
  await page.getByRole('button', { name: 'Создать дерево задачи' }).click()
  await page.getByLabel('Имя', { exact: true }).fill('Автор задачи')
  await page.getByRole('button', { name: 'Продолжить' }).click()
  await ready(page)
  await expect(page).toHaveURL(/\/tracker\/UI-100$/)
  await expect(root(page)).toHaveAttribute('data-text', 'UI-100')
  await expect(page.locator('.diagram-trigger > span:first-child')).toHaveText('UI-100')
  const id = await page.locator('main').getAttribute('data-diagram-id')
  await rename(page, 'Починить\nрусский отчёт')
  await expect(page.locator('.diagram-trigger > span:first-child')).toHaveText('UI-100 · Починить русский отчёт')
  await expect.poll(async () => (await (await page.request.get('/api/tracker/UI-100')).json()).title).toBe('Починить русский отчёт')
  await page.reload()
  await ready(page)
  await expect(page.locator('main')).toHaveAttribute('data-diagram-id', id!)
  await expect(root(page)).toHaveAttribute('data-text', 'Починить\nрусский отчёт')
  await rename(page, '')
  await expect(page.locator('.diagram-trigger > span:first-child')).toHaveText('UI-100')
})

test('existing tasks are guest-readable, shared across clients and separate from ordinary diagrams', async ({ page, browser }) => {
  await page.addInitScript(() => localStorage.setItem('decompose:participant-name:v1', 'Автор'))
  await page.goto('/tracker/UI-200')
  await ready(page)
  const id = await page.locator('main').getAttribute('data-diagram-id')
  const otherContext = await browser.newContext()
  const other = await otherContext.newPage()
  try {
    await other.goto('/tracker/ui-200')
    await ready(other)
    await expect(other.getByRole('dialog', { name: 'Представься' })).toHaveCount(0)
    await expect(other.locator('main')).toHaveAttribute('data-diagram-id', id!)
    await rename(page, 'Совместная задача')
    await expect(root(other)).toHaveAttribute('data-text', 'Совместная задача')
    await expect.poll(async () => (await (await page.request.get('/api/tracker/UI-200')).json()).title).toBe('Совместная задача')
    await page.evaluate(() => Object.assign(window, { trackerNavigationProbe: 'same-page' }))
    await page.getByRole('button', { name: 'Схемы', exact: true }).click()
    await expect(page.getByRole('group', { name: 'Раздел каталога' }).getByRole('button', { name: 'Задачи' })).toHaveAttribute('aria-pressed', 'true')
    await page.getByLabel('Поиск задач', { exact: true }).fill('СОВМЕСТНАЯ')
    await expect(page.getByRole('navigation', { name: 'Список задач' }).getByRole('link')).toHaveText(/UI-200 · Совместная задача/)
    await page.getByRole('group', { name: 'Раздел каталога' }).getByRole('button', { name: 'Схемы', exact: true }).click()
    await expect(page.locator(`.diagrams-list a[href="/?diagram=${id}"]`)).toHaveCount(0)
    await page.locator('.diagrams-list a[href="/?diagram=main"]').click()
    await ready(page)
    await expect(page.locator('main')).toHaveAttribute('data-diagram-id', 'main')
    await page.goBack()
    await ready(page)
    await expect(page).toHaveURL(/\/tracker\/UI-200$/)
    await expect(root(page)).toHaveAttribute('data-text', 'Совместная задача')
    expect(await page.evaluate(() => (window as unknown as { trackerNavigationProbe: string }).trackerNavigationProbe)).toBe('same-page')
    await page.setViewportSize({ width: 375, height: 667 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(375)
    await picker(page, 'Задачи')
    await expect(page.getByLabel('Поиск задач', { exact: true })).toBeInViewport()
    await expect(page.getByRole('navigation', { name: 'Список задач' }).getByRole('link').first()).toBeVisible()
    await page.screenshot({ path: 'test-results/tracker-mobile.png' })
  } finally { await otherContext.close() }
})

test('tracker picker paginates and searches the whole catalog by key and root text', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('decompose:participant-name:v1', 'Автор'))
  for (let i = 1; i <= 25; i++) expect((await page.request.post(`/api/tracker/PAGE-${i}`)).ok()).toBe(true)
  await page.goto('/tracker/PAGE-1')
  await ready(page)
  await rename(page, 'Уникальное описание ёж')
  await expect.poll(async () => (await (await page.request.get('/api/tracker/PAGE-1')).json()).title).toBe('Уникальное описание ёж')
  await picker(page, 'Задачи')
  const links = page.getByRole('navigation', { name: 'Список задач' }).getByRole('link')
  await expect(links).toHaveCount(20)
  await expect(links.first()).toHaveAttribute('href', '/tracker/PAGE-1')
  await page.screenshot({ path: 'test-results/tracker-picker.png' })
  const search = page.getByLabel('Поиск задач', { exact: true })
  await search.fill('page-')
  await expect(links).toHaveCount(20)
  await page.getByRole('button', { name: 'Показать ещё' }).click()
  await expect(links).toHaveCount(25)
  await search.fill('описание ЁЖ')
  await expect(links).toHaveCount(1)
  await expect(links).toHaveAttribute('href', '/tracker/PAGE-1')
  await search.fill('PAGE-999999')
  await expect(page.getByText('Задачи не найдены.')).toBeVisible()
  expect((await page.request.get('/api/tracker/PAGE-999999')).status()).toBe(404)
})

test('loaded tracker routes and cached search work offline and edits sync on reconnect', async ({ page, context }) => {
  await page.addInitScript(() => localStorage.setItem('decompose:participant-name:v1', 'Offline автор'))
  await page.goto('/tracker/OFF-1')
  await ready(page)
  await rename(page, 'Задача offline')
  await expect.poll(async () => (await (await page.request.get('/api/tracker/OFF-1')).json()).title).toBe('Задача offline')
  const before = await (await page.request.get('/api/tracker/OFF-1')).json()
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  await context.setOffline(true)
  await page.evaluate(() => dispatchEvent(new Event('offline')))
  await page.reload()
  await ready(page)
  await expect(page).toHaveURL(/\/tracker\/OFF-1$/)
  await expect(root(page)).toHaveAttribute('data-text', 'Задача offline')
  await picker(page, 'Задачи')
  await expect(page.getByText(/Поиск по сохранённому неполному каталогу/)).toBeVisible()
  await page.getByLabel('Поиск задач', { exact: true }).fill('OFF-1')
  await page.getByRole('navigation', { name: 'Список задач' }).getByRole('link').click()
  await ready(page)
  await rename(page, 'Изменено без сети')
  await navigate(page, '/tracker/OFF-999999')
  await expect(page.getByRole('alert')).toContainText('Для первого открытия этой задачи нужно соединение с сервером')
  await expect(page).toHaveURL(/\/tracker\/OFF-1$/)
  await expect(root(page)).toHaveAttribute('data-text', 'Изменено без сети')
  await context.setOffline(false)
  await page.evaluate(() => dispatchEvent(new Event('online')))
  await expect.poll(async () => (await (await page.request.get('/api/tracker/OFF-1')).json()).title).toBe('Изменено без сети')
  expect((await (await page.request.get('/api/tracker/OFF-1')).json()).updatedAt).toBeGreaterThan(before.updatedAt)
})

test('leaving a pending creation cancels its identity prompt without creating a task', async ({ page }) => {
  await page.goto('/')
  await ready(page)
  await navigate(page, '/tracker/CANCEL-1')
  await expect(page.getByRole('dialog', { name: 'Представься', exact: true })).toBeVisible()
  await page.goBack()
  await ready(page)
  await expect(page.getByRole('dialog', { name: 'Представься', exact: true })).toHaveCount(0)
  await expect(page.locator('main')).toHaveAttribute('data-diagram-id', 'main')
  expect((await page.request.get('/api/tracker/CANCEL-1')).status()).toBe(404)
})

test('late search responses do not overwrite the latest query', async ({ page }) => {
  await page.goto('/')
  await ready(page)
  await picker(page, 'Задачи')
  const item = await (await page.request.post('/api/tracker/RACE-1')).json()
  let release!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  let started = false
  await page.route('**/api/tracker?**', async route => {
    const query = new URL(route.request().url()).searchParams.get('q')
    if (query === 'первый') {
      started = true
      await gate
      await route.fulfill({ json: { items: [item], nextOffset: null } }).catch(() => {})
    } else await route.fulfill({ json: { items: [], nextOffset: null } })
  })
  try {
    await page.getByLabel('Поиск задач', { exact: true }).fill('первый')
    await expect.poll(() => started).toBe(true)
    await page.getByLabel('Поиск задач', { exact: true }).fill('последний')
    await expect(page.getByText('Задачи не найдены.')).toBeVisible()
    release()
    await expect(page.getByRole('navigation', { name: 'Список задач' }).getByRole('link')).toHaveCount(0)
    await expect(page.getByLabel('Поиск задач', { exact: true })).toHaveValue('последний')
  } finally { release() }
})

test('server errors do not create tasks and cancelling a transition retains the current diagram', async ({ page }) => {
  await page.goto('/')
  await ready(page)
  const posts: string[] = []
  page.on('request', request => { if (request.method() === 'POST' && request.url().includes('/api/tracker/')) posts.push(request.url()) })
  await page.route('**/api/tracker/FAIL-1', route => route.fulfill({ status: 503, json: { error: 'Сервер недоступен' } }))
  await navigate(page, '/tracker/FAIL-1')
  await expect(page.getByRole('alert')).toContainText('Сервер не смог открыть дерево задачи')
  await expect(page.getByRole('dialog', { name: 'Представься' })).toHaveCount(0)
  await expect(page).toHaveURL(/\/$/)
  await navigate(page, '/tracker/CANCEL-2')
  await expect(page.getByRole('dialog', { name: 'Представься', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await ready(page)
  await expect(page).toHaveURL(/\/$/)
  await expect(page.locator('main')).toHaveAttribute('data-diagram-id', 'main')
  expect(posts).toEqual([])
  expect((await page.request.get('/api/tracker/CANCEL-2')).status()).toBe(404)
})
