import { testDiagram } from './fixtures'
import { test, expect, type Page } from '@playwright/test'

const root = (page: Page) => page.locator('[data-cell-id="root"]')
const ready = async (page: Page) => {
  await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
}
async function rename(page: Page, text: string) {
  await root(page).dblclick()
  await page.getByRole('textbox', { name: 'Текст клеточки' }).fill(text)
  await page.keyboard.press('Enter')
  await expect(root(page)).toHaveAttribute('data-text', text)
}
async function picker(page: Page, section: 'Схемы' | 'Задачи') {
  await page.getByRole('button', { name: 'Схемы', exact: true }).click()
  await page.getByRole('tablist', { name: 'Раздел каталога' }).getByRole('tab', { name: section, exact: true }).click()
}
async function navigate(page: Page, path: string) {
  await page.evaluate(path => {
    history.pushState(null, '', path)
    dispatchEvent(new PopStateEvent('popstate'))
  }, path)
}

test('first tracker visit asks for a name, cancel creates nothing, retry initializes the key once', async ({ page }) => {
  await page.goto('/tracker/ui-100')
  const prompt = page.getByRole('dialog', { name: 'Представься', exact: true })
  await expect(prompt).toBeVisible()
  expect((await page.request.get('/api/tracker/UI-100')).status()).toBe(404)
  await prompt.getByRole('button', { name: 'Отмена' }).click()
  await expect(page.getByText('Дерево задачи ещё не создано.')).toBeVisible()
  expect((await page.request.get('/api/tracker/UI-100')).status()).toBe(404)
  await page.getByRole('button', { name: 'Создать дерево задачи' }).click()
  await page.getByLabel('Имя', { exact: true }).fill('Автор задачи')
  await page.getByRole('button', { name: 'Продолжить' }).click()
  await ready(page)
  await expect(page).toHaveURL(/\/tracker\/UI-100$/)
  await expect(root(page)).toHaveAttribute('data-text', 'UI-100')
  const trigger = page.locator('.diagram-trigger')
  await expect(trigger).toHaveClass(/tracker-trigger/)
  await expect(trigger).toHaveCSS('background-color', 'rgb(224, 239, 217)')
  await expect(trigger.locator('span:first-child')).toHaveText('UI-100')
  const id = await page.locator('main').getAttribute('data-diagram-id')
  await rename(page, 'Починить\nрусский отчёт')
  await expect(trigger.locator('span:first-child')).toHaveText('UI-100 · Починить русский отчёт')
  await expect.poll(async () => (await (await page.request.get('/api/tracker/UI-100')).json()).title).toBe('Починить русский отчёт')
  await page.reload()
  await ready(page)
  await expect(page.locator('main')).toHaveAttribute('data-diagram-id', id!)
  await expect(root(page)).toHaveAttribute('data-text', 'Починить\nрусский отчёт')
  await rename(page, '')
  await expect(trigger.locator('span:first-child')).toHaveText('UI-100')
})

test('task cards link to other task trees through F4, mouse and Ctrl+Enter', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('decompose:participant-name:v1', 'Автор ссылок'))
  await page.goto('/tracker/LINKSOURCE-1')
  await ready(page)
  await root(page).click()
  await page.keyboard.press('Tab')
  await page.getByRole('textbox', { name: 'Текст клеточки' }).fill('Связанная задача')
  await page.keyboard.press('Enter')
  const card = page.locator('[data-active="true"]')

  await expect(page.locator('main')).toBeFocused()
  await page.keyboard.press('F4')
  const dialog = page.getByRole('dialog', { name: 'Параметры карточки' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button').allTextContents()).resolves.toEqual(['Сохранить', 'Отмена'])
  const input = dialog.getByLabel('Ссылка на задачу')
  await input.fill('не ключ')
  await dialog.getByRole('button', { name: 'Сохранить' }).click()
  await expect(dialog.getByRole('alert')).toContainText('MC-99636')
  await input.fill('linktarget-2')
  await dialog.getByRole('button', { name: 'Сохранить' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(card).toHaveAttribute('data-tracker-link', 'LINKTARGET-2')
  const link = card.getByRole('link', { name: 'Открыть задачу LINKTARGET-2' })
  await expect(link).toHaveAttribute('href', 'tracker/LINKTARGET-2')

  await page.keyboard.press('Control+z')
  await expect(card).toHaveAttribute('data-tracker-link', '')
  await page.keyboard.press('Control+Shift+z')
  await expect(card).toHaveAttribute('data-tracker-link', 'LINKTARGET-2')
  await link.click()
  await ready(page)
  await expect(page).toHaveURL(/\/tracker\/LINKTARGET-2$/)
  await expect(root(page)).toHaveAttribute('data-text', 'LINKTARGET-2')

  await page.goBack()
  await ready(page)
  const restored = page.locator('[data-tracker-link="LINKTARGET-2"]')
  await restored.click()
  await page.keyboard.press('Control+Enter')
  await ready(page)
  await expect(page).toHaveURL(/\/tracker\/LINKTARGET-2$/)
})

test('management offers the same actions for diagrams and tasks and opens a typed key only on request', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('decompose:participant-name:v1', 'Автор'))
  await page.goto(await testDiagram(page)); await ready(page)
  await expect(page.locator('.diagram-trigger')).not.toHaveClass(/tracker-trigger/)
  await picker(page, 'Схемы')
  const current = page.getByRole('region', { name: 'Текущая схема' })
  await expect(current).toContainText('Внутренняя схема')
  await expect(current.locator('.storage-kind')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  const actions = ['Сохранить в файл', 'Перенести в файл', 'Заменить из файла', 'Удалить схему']
  await expect(current.getByRole('button')).toHaveText(actions)
  await page.getByRole('tablist', { name: 'Раздел каталога' }).getByRole('tab', { name: 'Задачи' }).click()
  await page.getByLabel('Поиск задач', { exact: true }).fill('mode-9981')
  const open = page.getByRole('button', { name: 'Создать', exact: true })
  await expect(open).toBeEnabled()
  expect((await page.request.get('/api/tracker/MODE-9981')).status()).toBe(404)
  await open.click(); await ready(page)
  await expect(page).toHaveURL(/\/tracker\/MODE-9981$/)
  await expect(root(page)).toHaveAttribute('data-text', 'MODE-9981')
  await expect(page.locator('.diagram-trigger')).toHaveClass(/tracker-trigger/)
  await picker(page, 'Задачи')
  await expect(current).toContainText('Задача')
  await expect(current.locator('.storage-kind')).toHaveCSS('background-color', 'rgb(224, 239, 217)')
  await expect(current.getByRole('button')).toHaveText(actions)
  for (const button of await current.getByRole('button').all()) await expect(button).toBeEnabled()
  await page.screenshot({ path: 'test-results/management-desktop.png' })
  await page.setViewportSize({ width: 375, height: 667 })
  const dialog = page.getByRole('dialog', { name: 'Выбор схемы для редактирования', exact: true })
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/management-mobile.png' })
})

test('task creation requires a checked unused key without whitespace', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('decompose:participant-name:v1', 'Автор'))
  await page.goto(await testDiagram(page)); await ready(page)
  await picker(page, 'Задачи')
  const search = page.getByLabel('Поиск задач', { exact: true })
  const create = page.getByRole('button', { name: 'Создать', exact: true })
  await expect(create).toBeVisible()
  await expect(create).toBeDisabled()
  for (const invalid of [' ', 'CREATE 71', 'CREATE- 71', ' CREATE-71', 'CREATE-71 ', 'CREATE-71\u00a0', 'описание задачи']) {
    await search.fill(invalid)
    await expect(create).toBeDisabled()
  }
  await search.fill('create-71')
  await expect(create).toBeEnabled()
  await search.dispatchEvent('keydown', { key: 'Enter', isComposing: true })
  await expect(search).toBeFocused()
  await page.keyboard.down('Enter')
  await expect(create).toBeFocused()
  await page.keyboard.down('Enter')
  await page.keyboard.up('Enter')
  expect((await page.request.get('/api/tracker/CREATE-71')).status()).toBe(404)
  await page.keyboard.press('Enter'); await ready(page)
  await expect(page).toHaveURL(/\/tracker\/CREATE-71$/)
  await expect(root(page)).toHaveAttribute('data-text', 'CREATE-71')
  await picker(page, 'Задачи')
  const checked = page.waitForResponse(response => response.url().endsWith('/api/tracker/CREATE-71') && response.request().method() === 'GET')
  await search.fill('create-71')
  expect((await checked).status()).toBe(200)
  await expect(create).toBeDisabled()
})

test('task search supports arrow selection and Enter opening without creation', async ({ page }) => {
  for (let index = 1; index <= 3; index++) await page.request.post(`/api/tracker/KEYBOARD-${index}`)
  await page.goto(await testDiagram(page)); await ready(page)
  await picker(page, 'Задачи')
  let posts = 0
  page.on('request', request => { if (request.method() === 'POST' && request.url().includes('/api/tracker/')) posts++ })
  const search = page.getByLabel('Поиск задач', { exact: true })
  const links = page.getByRole('navigation', { name: 'Список задач' }).getByRole('link')
  await search.fill('KEYBOARD-')
  await expect(links).toHaveCount(3)
  const last = await links.last().getAttribute('href')
  await search.press('ArrowUp')
  await expect(links.last()).toBeFocused()
  await expect(search).toHaveValue('KEYBOARD-')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(new RegExp(`/${last}$`))
  await picker(page, 'Задачи')
  await search.fill('KEYBOARD-')
  await expect(links).toHaveCount(3)
  const second = await links.nth(1).getAttribute('href')
  await search.press('ArrowDown')
  await expect(links.first()).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(links.nth(1)).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(new RegExp(`/${second}$`))
  await picker(page, 'Задачи')
  await search.fill('KEYBOARD-')
  await expect(links).toHaveCount(3)
  const first = await links.first().getAttribute('href')
  await search.dispatchEvent('keydown', { key: 'Enter', isComposing: true })
  await expect(search).toBeFocused()
  await search.press('Enter')
  await expect(page).toHaveURL(new RegExp(`/${first}$`))
  expect(posts).toBe(0)
})

test('an existing task beyond the first search page cannot be created', async ({ page }) => {
  await page.request.post('/api/tracker/EXACT-1')
  for (let i = 100; i < 125; i++) await page.request.post(`/api/tracker/EXACT-${i}`)
  await page.goto(await testDiagram(page)); await ready(page)
  await picker(page, 'Задачи')
  const checked = page.waitForResponse(response => response.url().endsWith('/api/tracker/EXACT-1'))
  await page.getByLabel('Поиск задач', { exact: true }).fill('exact-1')
  expect((await checked).status()).toBe(200)
  const links = page.getByRole('navigation', { name: 'Список задач' }).getByRole('link')
  await expect(links).toHaveCount(20)
  await expect(page.locator('.diagrams-list a[href="tracker/EXACT-1"]')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Создать', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Показать ещё' }).click()
  await expect(links).toHaveCount(26)
  await expect(page.getByRole('button', { name: 'Создать', exact: true })).toBeDisabled()
})

test.describe('controlled tracker availability', () => {
test.use({ serviceWorkers: 'block' })

test('task creation stays disabled during lookup, after lookup errors and offline', async ({ page, context }) => {
  await page.goto(await testDiagram(page)); await ready(page)
  await picker(page, 'Задачи')
  const search = page.getByLabel('Поиск задач', { exact: true })
  const create = page.getByRole('button', { name: 'Создать', exact: true })
  let release!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/tracker/CHECK-1', async route => {
    await gate
    await route.fulfill({ status: 404, json: { error: 'Нет дерева' } })
  })
  const requested = page.waitForRequest('**/api/tracker/CHECK-1')
  await search.fill('CHECK-1')
  await requested
  await expect(create).toBeDisabled()
  await search.press('Enter')
  await expect(search).toBeFocused()
  await search.press('ArrowDown')
  await expect(search).toBeFocused()
  release()
  await expect(create).toBeEnabled()
  await page.route('**/api/tracker/CHECK-2', route => route.fulfill({ status: 503, json: { error: 'Ошибка' } }))
  const failed = page.waitForResponse('**/api/tracker/CHECK-2')
  await search.fill('CHECK-2')
  await expect(create).toBeDisabled()
  await failed
  await expect(create).toBeDisabled()
  await search.press('Enter')
  await expect(search).toBeFocused()
  await context.setOffline(true)
  await search.fill('CHECK-3')
  await expect(page.getByText('Сервер недоступен. Поиск по сохранённому неполному каталогу;', { exact: false })).toBeVisible()
  await expect(create).toBeDisabled()
  await search.press('Enter')
  await expect(search).toBeFocused()
})
})

test('existing tasks are guest-readable, shared across clients and separate from ordinary diagrams', async ({ page, browser }) => {
  const ordinaryUrl = await testDiagram(page)
  await page.addInitScript(() => localStorage.setItem('decompose:participant-name:v1', 'Автор'))
  await page.goto('/tracker/UI-200')
  await ready(page)
  const id = await page.locator('main').getAttribute('data-diagram-id')
  const otherContext = await browser.newContext()
  const other = await otherContext.newPage()
  try {
    await other.goto('/tracker/ui-200')
    await ready(other)
    await expect(other.getByRole('dialog', { name: 'Представься' })).toHaveCount(0)
    await expect(other.locator('main')).toHaveAttribute('data-diagram-id', id!)
    await rename(page, 'Совместная задача')
    await expect(root(other)).toHaveAttribute('data-text', 'Совместная задача')
    await expect.poll(async () => (await (await page.request.get('/api/tracker/UI-200')).json()).title).toBe('Совместная задача')
    await page.evaluate(() => Object.assign(window, { trackerNavigationProbe: 'same-page' }))
    await page.getByRole('button', { name: 'Схемы', exact: true }).click()
    await expect(page.getByRole('tablist', { name: 'Раздел каталога' }).getByRole('tab', { name: 'Задачи' })).toHaveAttribute('aria-selected', 'true')
    await page.getByLabel('Поиск задач', { exact: true }).fill('СОВМЕСТНАЯ')
    await expect(page.getByRole('navigation', { name: 'Список задач' }).getByRole('link')).toHaveText(/UI-200 · Совместная задача/)
    await page.getByRole('tablist', { name: 'Раздел каталога' }).getByRole('tab', { name: 'Схемы', exact: true }).click()
    await expect(page.locator(`.diagrams-list a[href="diagram/${id}"]`)).toHaveCount(0)
    await page.locator(`.diagrams-list a[href="diagram/${ordinaryUrl.split('/').pop()}"]`).click()
    await ready(page)
    await expect(page.locator('main')).toHaveAttribute('data-diagram-id', ordinaryUrl.split('/').pop()!)
    await page.goBack()
    await ready(page)
    await expect(page).toHaveURL(/\/tracker\/UI-200$/)
    await expect(root(page)).toHaveAttribute('data-text', 'Совместная задача')
    expect(await page.evaluate(() => (window as unknown as { trackerNavigationProbe: string }).trackerNavigationProbe)).toBe('same-page')
    await page.setViewportSize({ width: 375, height: 667 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(375)
    await picker(page, 'Задачи')
    await expect(page.getByLabel('Поиск задач', { exact: true })).toBeInViewport()
    await expect(page.getByRole('navigation', { name: 'Список задач' }).getByRole('link').first()).toBeVisible()
    await page.screenshot({ path: 'test-results/tracker-mobile.png' })
  } finally { await otherContext.close() }
})

test('tracker picker paginates and searches the whole catalog by key and root text', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('decompose:participant-name:v1', 'Автор'))
  for (let i = 1; i <= 25; i++) expect((await page.request.post(`/api/tracker/PAGE-${i}`)).ok()).toBe(true)
  await page.goto('/tracker/PAGE-1')
  await ready(page)
  await rename(page, 'Уникальное описание ёж')
  await expect.poll(async () => (await (await page.request.get('/api/tracker/PAGE-1')).json()).title).toBe('Уникальное описание ёж')
  await picker(page, 'Задачи')
  const links = page.getByRole('navigation', { name: 'Список задач' }).getByRole('link')
  await expect(links).toHaveCount(20)
  await expect(links.first()).toHaveAttribute('href', 'tracker/PAGE-1')
  await page.screenshot({ path: 'test-results/tracker-picker.png' })
  const search = page.getByLabel('Поиск задач', { exact: true })
  await search.fill('page-')
  await expect(links).toHaveCount(20)
  await page.getByRole('button', { name: 'Показать ещё' }).click()
  await expect(links).toHaveCount(25)
  await search.fill('описание ЁЖ')
  await expect(links).toHaveCount(1)
  await expect(links).toHaveAttribute('href', 'tracker/PAGE-1')
  await search.fill('PAGE-999999')
  await expect(page.getByText('Задачи не найдены.')).toBeVisible()
  expect((await page.request.get('/api/tracker/PAGE-999999')).status()).toBe(404)
})

test('loaded tracker routes and cached search work offline and edits sync on reconnect', async ({ page, context }) => {
  await page.addInitScript(() => localStorage.setItem('decompose:participant-name:v1', 'Offline автор'))
  await page.goto('/tracker/OFF-1')
  await ready(page)
  await rename(page, 'Задача offline')
  await expect.poll(async () => (await (await page.request.get('/api/tracker/OFF-1')).json()).title).toBe('Задача offline')
  const before = await (await page.request.get('/api/tracker/OFF-1')).json()
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  await context.setOffline(true)
  await page.evaluate(() => dispatchEvent(new Event('offline')))
  await page.reload()
  await ready(page)
  await expect(page).toHaveURL(/\/tracker\/OFF-1$/)
  await expect(root(page)).toHaveAttribute('data-text', 'Задача offline')
  await picker(page, 'Задачи')
  await expect(page.getByText(/Поиск по сохранённому неполному каталогу/)).toBeVisible()
  await page.getByLabel('Поиск задач', { exact: true }).fill('OFF-1')
  await page.getByRole('navigation', { name: 'Список задач' }).getByRole('link').click()
  await ready(page)
  await rename(page, 'Изменено без сети')
  await navigate(page, '/tracker/OFF-999999')
  await expect(page.getByRole('alert')).toContainText('Для первого открытия этой задачи нужно соединение с сервером')
  await expect(page).toHaveURL(/\/tracker\/OFF-1$/)
  await expect(root(page)).toHaveAttribute('data-text', 'Изменено без сети')
  await context.setOffline(false)
  await page.evaluate(() => dispatchEvent(new Event('online')))
  await expect.poll(async () => (await (await page.request.get('/api/tracker/OFF-1')).json()).title).toBe('Изменено без сети')
  expect((await (await page.request.get('/api/tracker/OFF-1')).json()).updatedAt).toBeGreaterThan(before.updatedAt)
})

test('leaving a pending creation cancels its identity prompt without creating a task', async ({ page }) => {
  await page.goto(await testDiagram(page))
  await ready(page)
  await navigate(page, '/tracker/CANCEL-1')
  await expect(page.getByRole('dialog', { name: 'Представься', exact: true })).toBeVisible()
  await page.goBack()
  await ready(page)
  await expect(page.getByRole('dialog', { name: 'Представься', exact: true })).toHaveCount(0)
  await expect(page.locator('main')).toHaveAttribute('data-diagram-id', (await testDiagram(page)).split('/').pop()!)
  expect((await page.request.get('/api/tracker/CANCEL-1')).status()).toBe(404)
})

test('late search responses do not overwrite the latest query', async ({ page }) => {
  await page.goto(await testDiagram(page))
  await ready(page)
  await picker(page, 'Задачи')
  const item = await (await page.request.post('/api/tracker/RACE-1')).json()
  let release!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  let started = false
  await page.route('**/api/tracker?**', async route => {
    const query = new URL(route.request().url()).searchParams.get('q')
    if (query === 'первый') {
      started = true
      await gate
      await route.fulfill({ json: { items: [item], nextOffset: null } }).catch(() => {})
    } else await route.fulfill({ json: { items: [], nextOffset: null } })
  })
  try {
    await page.getByLabel('Поиск задач', { exact: true }).fill('первый')
    await expect.poll(() => started).toBe(true)
    await page.getByLabel('Поиск задач', { exact: true }).fill('последний')
    await expect(page.getByText('Задачи не найдены.')).toBeVisible()
    release()
    await expect(page.getByRole('navigation', { name: 'Список задач' }).getByRole('link')).toHaveCount(0)
    await expect(page.getByLabel('Поиск задач', { exact: true })).toHaveValue('последний')
  } finally { release() }
})

test('server errors do not create tasks and cancelling a transition retains the current diagram', async ({ page }) => {
  await page.goto(await testDiagram(page))
  await ready(page)
  const posts: string[] = []
  page.on('request', request => { if (request.method() === 'POST' && request.url().includes('/api/tracker/')) posts.push(request.url()) })
  await page.route('**/api/tracker/FAIL-1', route => route.fulfill({ status: 503, json: { error: 'Сервер недоступен' } }))
  await navigate(page, '/tracker/FAIL-1')
  await expect(page.getByRole('alert')).toContainText('Сервер не смог открыть дерево задачи')
  await expect(page.getByRole('dialog', { name: 'Представься' })).toHaveCount(0)
  await expect(page).toHaveURL(await testDiagram(page))
  await navigate(page, '/tracker/CANCEL-2')
  await expect(page.getByRole('dialog', { name: 'Представься', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await ready(page)
  await expect(page).toHaveURL(await testDiagram(page))
  await expect(page.locator('main')).toHaveAttribute('data-diagram-id', (await testDiagram(page)).split('/').pop()!)
  expect(posts).toEqual([])
  expect((await page.request.get('/api/tracker/CANCEL-2')).status()).toBe(404)
})
