import { testDiagram } from './fixtures'
import { test, expect, namedContext, type Page } from './fixtures'

async function open(page: Page) {
  await page.goto(await testDiagram(page))
  await expect(page.locator('main')).toHaveAttribute('data-ready', 'true')
  await expect(page.getByTestId('connection')).toHaveAttribute('data-connected', 'true')
}
function cell(page: Page, text: string) { return page.locator('[data-cell-id]').filter({ has: page.locator('.cell-text', { hasText: text }) }) }
async function child(page: Page, text: string) {
  await page.locator('[data-cell-id="root"]').click()
  await page.keyboard.press('Tab')
  await page.getByRole('textbox').fill(text)
  await page.keyboard.press('Control+Enter')
  await expect(page.locator('[data-cell-id][data-active="true"]')).toHaveAttribute('data-text', text)
}

test('keyboard decomposition, atomic drafts, cancel and status', async ({ page }) => {
  await open(page)
  await child(page, 'План клавиатурой')
  const id = await cell(page, 'План клавиатурой').getAttribute('data-cell-id')
  await page.keyboard.press('Tab')
  await page.getByRole('textbox').fill('Первая деталь')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('textbox')).toHaveCount(0)
  await page.keyboard.press('Enter')
  await page.getByRole('textbox').fill('Вторая деталь')
  await page.keyboard.press('Control+Enter')
  await expect(cell(page, 'Вторая деталь')).toHaveAttribute('data-parent-id', id!)
  await page.keyboard.press('Control+ArrowUp')
  await expect(cell(page, 'Вторая деталь')).toHaveAttribute('data-order', '0')
  await page.keyboard.press('Space')
  await expect(cell(page, 'Вторая деталь')).toHaveAttribute('data-status', 'done')
  await page.keyboard.press('F2')
  await page.getByRole('textbox').fill('Отменённый draft')
  await page.keyboard.press('Escape')
  await expect(cell(page, 'Вторая деталь')).toBeVisible()
  await page.keyboard.press('Tab')
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-cell-id][data-active="true"]')).toHaveAttribute('data-text', 'Вторая деталь')
  await page.keyboard.press('Shift+Tab')
  await expect(cell(page, 'Вторая деталь')).toHaveAttribute('data-parent-id', 'root')
  await page.keyboard.press('Delete')
  await expect(cell(page, 'Вторая деталь')).toHaveCount(0)
})

test('two clients, soft lock, offline reload and concurrent atomic text merge', async ({ browser }) => {
  const leftContext = await namedContext(browser)
  const rightContext = await namedContext(browser)
  const left = await leftContext.newPage()
  const right = await rightContext.newPage()
  try {
    await open(left)
    await open(right)
    await child(left, 'Совместная клеточка')
    const id = await cell(left, 'Совместная клеточка').getAttribute('data-cell-id')
    const target = (page: Page) => page.locator(`[data-cell-id="${id}"]`)
    await expect(target(right)).toHaveAttribute('data-text', 'Совместная клеточка')
    await expect(left.locator('.avatars span')).toHaveCount(2)
    await left.keyboard.press('F2')
    await left.getByRole('textbox').fill('Локальный draft')
    await expect(target(right)).toHaveAttribute('data-text', 'Совместная клеточка')
    await expect(target(right)).toHaveAttribute('data-editing-by', /Участник/)
    await expect(target(right)).toHaveText('Совместная клеточка')
    await target(right).click()
    await right.keyboard.press('F2')
    await expect(right.getByRole('textbox')).toHaveCount(0)
    await expect(right.getByRole('alert')).toContainText('сейчас редактирует эту клеточку')
    await right.getByRole('button', { name: 'Закрыть сообщение' }).click()
    await expect(right.getByRole('alert')).toHaveCount(0)
    await left.keyboard.press('Control+Enter')
    await expect(target(right)).toHaveAttribute('data-text', 'Локальный draft')

    await left.evaluate(async () => { await navigator.serviceWorker.ready })
    await right.evaluate(async () => { await navigator.serviceWorker.ready })
    await leftContext.setOffline(true)
    await rightContext.setOffline(true)
    await left.evaluate(() => window.dispatchEvent(new Event('offline')))
    await right.evaluate(() => window.dispatchEvent(new Event('offline')))
    await expect(left.getByTestId('connection')).toHaveAttribute('data-connected', 'false')
    await left.keyboard.press('F2')
    await left.getByRole('textbox').fill('Полная версия слева')
    await left.keyboard.press('Control+Enter')
    await right.keyboard.press('F2')
    await right.getByRole('textbox').fill('Полная версия справа')
    await right.keyboard.press('Control+Enter')
    // Новая сессия должна читать уже закоммиченные изменения из IndexedDB.
    await left.waitForTimeout(250)
    await left.reload()
    await expect(left.locator('main')).toHaveAttribute('data-ready', 'true')
    await expect(target(left)).toHaveAttribute('data-text', 'Полная версия слева')
    await leftContext.setOffline(false)
    await rightContext.setOffline(false)
    await left.evaluate(() => window.dispatchEvent(new Event('online')))
    await right.evaluate(() => window.dispatchEvent(new Event('online')))
    await expect(left.getByTestId('connection')).toHaveAttribute('data-connected', 'true')
    await expect(right.getByTestId('connection')).toHaveAttribute('data-connected', 'true')
    await expect.poll(async () => (await target(left).getAttribute('data-text')) === (await target(right).getAttribute('data-text'))).toBe(true)
    expect(['Полная версия слева', 'Полная версия справа']).toContain(await target(left).getAttribute('data-text'))

    await target(left).click()
    await left.keyboard.press('Delete')
    await expect(target(right)).toHaveCount(0)
    await expect(right.locator('[data-cell-id][data-active="true"]')).toHaveCount(1)
    await left.screenshot({ path: 'test-results/workspace.png', fullPage: true })
  } finally {
    await leftContext.close()
    await rightContext.close()
  }
})

test('indent, automatic height and remote subtree deletion while editing', async ({ browser }) => {
  const leftContext = await namedContext(browser)
  const rightContext = await namedContext(browser)
  const left = await leftContext.newPage()
  const right = await rightContext.newPage()
  try {
    await open(left)
    await open(right)
    await child(left, 'Проверка поддерева')
    const parentId = await cell(left, 'Проверка поддерева').getAttribute('data-cell-id')
    await left.keyboard.press('Tab')
    await left.getByRole('textbox').fill('Вложенный родитель')
    await left.keyboard.press('Enter')
    await left.keyboard.press('Enter')
    const longText = 'Длинная мысль с автоматическим переносом. '.repeat(8).trim()
    await left.getByRole('textbox').fill(longText)
    await left.keyboard.press('Control+Enter')
    const long = cell(left, longText)
    const longId = await long.getAttribute('data-cell-id')
    const nestedId = await cell(left, 'Вложенный родитель').getAttribute('data-cell-id')
    await expect.poll(() => long.evaluate(element => element.clientHeight)).toBeGreaterThan(200)
    await left.keyboard.press('Control+ArrowRight')
    await expect(long).toHaveAttribute('data-parent-id', nestedId!)
    await left.keyboard.press('Shift+Tab')
    await expect(long).toHaveAttribute('data-parent-id', parentId!)
    await left.keyboard.press('ArrowUp')
    await expect(left.locator('[data-active="true"]')).toHaveAttribute('data-cell-id', nestedId!)
    await left.keyboard.press('ArrowRight')
    await expect(left.locator('[data-active="true"]')).toHaveAttribute('data-cell-id', nestedId!)
    await left.keyboard.press('ArrowDown')
    await expect(left.locator('[data-active="true"]')).toHaveAttribute('data-cell-id', longId!)
    await left.keyboard.press('ArrowLeft')
    await expect(left.locator('[data-active="true"]')).toHaveAttribute('data-cell-id', parentId!)

    await right.locator(`[data-cell-id="${longId}"]`).click()
    await right.keyboard.press('F2')
    await right.getByRole('textbox').fill('Несохранённый draft удаляемого узла')
    await left.keyboard.press('Delete')
    await expect(left.locator(`[data-cell-id="${parentId}"]`)).toHaveCount(0)
    await expect(right.locator(`[data-cell-id="${longId}"]`)).toHaveCount(0)
    await expect(right.getByRole('textbox')).toHaveCount(0)
    await expect(right.locator('[data-active="true"]')).toHaveAttribute('data-cell-id', 'root')
    await expect(right.locator('main')).toBeFocused()
    await right.keyboard.press('Enter')
    await expect(right.locator('main')).toBeFocused()
    await right.keyboard.press('Tab')
    await expect(right.getByRole('textbox')).toBeFocused()
    await right.keyboard.press('Escape')
  } finally {
    await leftContext.close()
    await rightContext.close()
  }
})
